### ISSUE TITLE
Idea: Content Templates (aka Blueprints)

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-inner-content#20]
Could Inner Content leverage the use of Content Templates (aka Blueprints) for content selection?

The use-case would be to pre-configure a content block, then let it be selectable from the Content Type picker overlay.  We could attempt to re-use Umbraco's UI here?

> This is open to community feedback.

**Comment by leekelleher** [comment]
> _Dev notes - as we investigate..._

Here are the components from Umbraco... the view and controller:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/content/create.html

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js

The issue with the view is that it contains the dialog footer, along with the "Do something else" button/action.

The controller is tightly bound with the call to `contentTypeResource.getAllowedTypes` - which is based on the content node id.

I'm not sure how we could get around either of those issues.  We'll most likely need to copy code from Umbraco core.

**Comment by mattbrailsford** [comment]
Sounds like it'll be the simpler and less error prone option.

**Comment by leekelleher** [comment]
We'll need to bump up minimum Umbraco version to v7.7.0 - any issues with that?

**Comment by mattbrailsford** [comment]
is it needed from a dll reference perspective? Or just from JS perspective? As could do a client side version check and only allow that feature if 7.7 and above?

**Comment by leekelleher** [comment]
We need it for a ContentService API call, [`GetBlueprintsForContentTypes`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Services/ContentService.cs#L2133).

**Comment by mattbrailsford** [comment]
So really, that could be checked client side, and just not make the API call for older versions? Maybe this is all too much though given inner content is new anyway? What version are we targeting currently?

**Comment by leekelleher** [comment]
Currently targeting 7.4.0.  We could do this as a "breaking change" and bump up to a v2? (with no immediate rush in doing that)

**Comment by leekelleher** [comment]
Closing this ticket. We can discuss the implementation on PR #23
