### ISSUE TITLE
PreValue config - swap dropdown with a "Doc Type Picker"

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-inner-content#24]
Rather than using a dropdown, we could do similar to how the DocType "Allow children" permission UI works. Use the overlay directive to display a doctype picker.

https://github.com/umco/umbraco-inner-content/blob/develop/src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/views/innercontent.doctypepicker.html#L20

This is purely a cosmetic / consistent UI idea.

**Comment by leekelleher** [comment]
I'm thinking along the lines of the List View's layout control...

![capture](https://user-images.githubusercontent.com/209066/42509511-0b8bf1c4-8444-11e8-8d01-bcb731019058.PNG)

Where the "icon" picker would be a document-type, the "Name" and "Layout path" would be for the Name Template and Tab dropdown respectively.

**Comment by dnwhte** [comment]
Considering tackling this along with #43 since both involve changes to the doctypepicker. You mention "Tab dropdown". Inner Content currently doesn't have a Tab dropdown and supports tabs in the edit view. Are there plans to change this?

**Comment by leekelleher** [comment]
Ignore the Tab drop-down, we removed the feature in v2.0, 15a7d44d5603d91aa2053b1d773a4d7d0eca347b

**Comment by dnwhte** [comment]
Quick prototype 
![2019-01-18_16-32-46](https://user-images.githubusercontent.com/636470/51419404-23431800-1b3f-11e9-940d-642be30e8d43.gif)

**Comment by leekelleher** [comment]
The prototype looks great, thanks! 🎉 

Couple of technical points...

1. Let me know if the JSON value/schema changes for the prevalue data. There are things we can do to manipulate it, in order to keep backwards-compatibility. (I've got code examples where we've done this previously).  If there are no changes, then no worries. 🙂 
2. With the PR for this, you mention about #43 too.  If you could do them as separate PRs, that'd be great, otherwise it becomes trickier to review.

**Comment by dnwhte** [comment]
No changes to prevalue data needed. I will submit as a separate PR.

One question, do you feel it is safe to use the existing list classes in core or should I copy the styles and create new classes?

**Comment by dnwhte** [comment]
No changes to prevalue data needed. I will submit as a separate PR.

One question, do you feel it is safe to use the existing list classes in core or should I copy the styles and create new classes?

**Comment by leekelleher** [comment]
I'm happy to use the existing list classes.

**Comment by leekelleher** [comment]
Closing this ticket as a PR has been submitted. Further discussion can be had on PR #45 - thanks @dnwhte! 🎉
