### ISSUE TITLE
Courier fails if Inner-Node is empty

### ISSUE THREAD

**Issue by nielslyngsoe** [umco/umbraco-inner-content#39]
In my test I created a Stacked Content Data-Type, lets call it "Configuration".
In this Stacked Content you can create a Inner-Nodes that does not have any properties. Example: "Gather News articles", which is just a node with no properties. Cause that Node-Alias is giving the necessary data to the template.
When transferring this setup between environments, courier fails.

This can of course be fixed by just adding a Label to the empty Doc-Type.

Hope the issue makes sense, thanks.

**Comment by leekelleher** [comment]
Hi @nielslyngsoe, thanks for raising this - I haven't experienced that myself, but it would be an issue with the Courier data-resolver for Inner Content.

Would you be able to raise the issue over on the Courier Contrib repo, please?
https://github.com/umbraco/Umbraco.Courier.Contrib/issues

I'm not sure if this applies to Umbraco Deploy too?

Thanks!

**Comment by leekelleher** [comment]
Closing this ticket off. It has been raised on the Umbraco Courier Contrib issue tracker: <https://github.com/umbraco/Umbraco.Courier.Contrib/issues/45>
