### ISSUE TITLE
Prefix ContentTypeAliasPropertyKey with an underscore?

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-inner-content#4]
I'm wondering whether we should prefix the InnerContent specific properties with an underscore?

This would avoid any potential clashes with Umbraco property-alias names.

e.g. `ContentTypeAliasPropertyKey = "_contentTypeAlias"`

> :smirk: _maybe a double underscore might look better?_

Would there be any technical reasons to not do this? e.g. would Angular work okay with this?

---

@mattbrailsford - No biggie if you don't like the idea 😃

**Comment by mattbrailsford** [comment]
@leekelleher they are all prefixed with "ic" already

**Comment by leekelleher** [comment]
@mattbrailsford I was suggesting it as a replacement for the "ic" prefix.  _Of course, I know we're already using it..._ was more thinking about how to avoid any potential clashes.

_I'm happy for this to remain closed, just wanted to ask the question_ 😈

**Comment by mattbrailsford** [comment]
Why would '_' clash less than 'ic'?

**Comment by leekelleher** [comment]
Coz you can't use it as a property alias (in the DocType editor).

**Comment by mattbrailsford** [comment]
Ahh gotcha, though I still prefer 'ic' as then you know it's ours if
someone else implemented something similar.

**Comment by mattbrailsford** [comment]
Could go '_ic' though I guess? Best of both worlds?

**Comment by leekelleher** [comment]
I'm cool to stick with "ic" ... it was just one of those niggles that played on my mind 😉 
...and I'm trying to figure out how we'd actually make the switch over (without borking all existing data).

**Comment by mattbrailsford** [comment]
There is that :) who would be dumb enough to name a property
"icContentTypeAlias" anyway?

**Comment by leekelleher** [comment]
Touché!

![](http://marriedtothesea.com/011313/touche-touche.gif)

**Comment by leekelleher** [comment]
@mattbrailsford LOL, I should have gone with this one...

![](http://memecrunch.com/meme/4A5JZ/touche-my-friend/image.jpg)
