### ISSUE TITLE
404 GetAllContentTypes when adding stacked content as new data type

### ISSUE THREAD

**Issue by SemVC7** [umco/umbraco-inner-content#40]
Hi there,

I'm trying to add a new Data Type in Umbraco with the property editor Stacked content. When selecting "stacked content" i get the following error message.

Request error: The URL returned a 404 (not found): 
/~/umbraco/backoffice/InnerContent/InnerContentApi/GetAllContentTypes

I tried uninstall Our.Umbraco.InnerContent and Our.Umbraco.StackedContent, and the reinstall them again with the same results...

Can someone please help me fix this issue?

Thanks in advance

**Comment by leekelleher** [comment]
Hi @SemVC7, unfortunately the issue it due to a Chrome update, that breaks on older versions of Umbraco (and certain packages).

All the details are here: https://umbraco.com/blog/chrome-66-causing-errors-on-some-umbraco-sites/

**Comment by SemVC7** [comment]
Hi @leekelleher, thanks for getting in touch!

This problem also occurs when trying in Firefox. So I think it's not browser related.
The Umbraco version I'm using = Umbraco version 7.9.0

Any other ideas?

**Comment by leekelleher** [comment]
Maybe Firefox have introduce the `trimStart` JS function too? (I'm not too sure)

If your Umbraco site was upgraded, could it be possible that the "~/Umbraco/lib/umbraco/Extensions.js" file might have been not upgraded?

Either way, it's not a bug with Stacked Content (Inner Content) - as in there's nothing we can do to fix it in the package itself.

**Comment by SemVC7** [comment]
> Maybe Firefox have introduce the `trimStart` JS function too? (I'm not too sure)
> 
> If your Umbraco site was upgraded, could it be possible that the "~/Umbraco/lib/umbraco/Extensions.js" file might have been not upgraded?
> 
> Either way, it's not a bug with Stacked Content (Inner Content) - as in there's nothing we can do to fix it in the package itself.

My Umbraco website was a fresh install of version 7.9.0. I'll try and figure it out and will let you know if there is any news on this.

**Comment by leekelleher** [comment]
> My Umbraco website was a fresh install of version 7.9.0. 

Hmmm, I'm curious what might be causing this 🤔 

First place to check is the "/Umbraco/lib/umbraco/Extensions.js" file... find the `String.prototype.trimStart` code and make sure that it is wrapped with a `if (!String.prototype.trimStart)` check.

> Details are outlined here: <https://issues.umbraco.org/issue/U4-11253>

**Comment by SemVC7** [comment]
Yes I followed the instructions from https://issues.umbraco.org/issue/U4-11253 and now it's working as expected. 

I hope this workaround is seen by all people who have the same issue like me.

Thanks for helping me out ;-)

**Comment by leekelleher** [comment]
Actually, looking at the Umbraco version numbers, you'd need to be on v7.9.6+ to have the fix in place.

**Comment by SemVC7** [comment]
Ooooow that explains! I missed that, where did you find this info?

**Comment by leekelleher** [comment]
I keep an "unofficial" archive of all the Umbraco releases, along with release dates...

<http://code.leekelleher.com/umbraco/archive/>

The Umbraco blog post was on 20th April, so I checked against the release dates.  v7.9.0 was 26th Feb.

Out of curiosity, when did you install Umbraco? If it was in Feb, would you consider upgrading? If it was more recent, did you deliberately choose v7.9.0? _Not judging, only curious._

**Comment by SemVC7** [comment]
> I keep an "unofficial" archive of all the Umbraco releases, along with release dates...
> 
> http://code.leekelleher.com/umbraco/archive/
> 
> The Umbraco blog post was on 20th April, so I checked against the release dates. v7.9.0 was 26th Feb.
> 
> Out of curiosity, when did you install Umbraco? If it was in Feb, would you consider upgrading? If it was more recent, did you deliberately choose v7.9.0? _Not judging, only curious._

I did this fresh install long time ago indeed... I will update to the latest stable version :-)
