### ISSUE TITLE
ContentEditorOverlay is not wide enough to show Related Links

### ISSUE THREAD

**Issue by Migaroez** [umco/umbraco-inner-content#48]
![image](https://user-images.githubusercontent.com/6025797/52275843-f3727d80-2950-11e9-8b71-3c936459de8b.png)

If i add `style="width: 700px;"` to innercontent.overlay,html on the second `umb-overlay` Then its works.

Would be handy if the width of the editor could be set in a config somewhere.

**Comment by leekelleher** [comment]
Hi @Migaroez, thanks for raising this.

We have a new feature in the next release (upcoming v2.0.3) which adds CSS classes to the overlay/modal, see #42 and https://github.com/umco/umbraco-stacked-content/issues/61 for background info.

We don't have a current schedule for the next release. I want to do it soon, but juggling home & work life at the moment.

I'll close off this ticket now.
