### ISSUE TITLE
More robust insert content overlay

### ISSUE THREAD

**Issue by danwhite85** [umco/umbraco-inner-content#9]
The insert content overlay is cumbersome and difficult to navigate for editors when there are a large number of components. Something more robust than the item picker is needed. It could be that the entire UX of the insert content overlay needs to be rethought (as the issue exist within , but at the very least search filtering and component grouping would be helpful.

**Comment by jamiepollock** [comment]
@danwhite85 are you thinking along the same lines as the data type picker overlay?

One potential solution is opting for the right hand panel which offers a bit more screen space than the centralised modal than currently opens.

I think the data type picker style panel would be great. Even with some applications only have as many as 3 or 4 inner content items it still would allow users a bit more space without feeling like overkill.

**Comment by leekelleher** [comment]
@danwhite85 I'm going to close this ticket off, I still like your suggestion and open to further discussion on PR #18.

**Comment by leekelleher** [comment]
Just to let you guys know that we've got a work-in-progress for this in PR #23
